application: pointoutapp
version: prototype
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /images
  static_dir: images

- url: /
  static_files: index.html
  upload: index.html

- url: /.*
  script: pointout.py

builtins:
- datastore_admin: on
- appstats: on
